<?php

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "fairytalewedding";
// $base_url="://localhost:8081/asmakgroup/"
$connF = mysqli_connect(hostname: $servername, username: $username, password: $password, database: $dbname);

if ($connF) {
	echo "";
} else {
	echo "connection failed";
}


function generateRandomPassword()
{

	$combination = 'qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM0123456789~!@#$%^&*()_+[]{}<>?';
	$combination = str_shuffle($combination);
	$randomPassword = substr($combination, 0, 8);
	return $randomPassword;
}

function sentConfirmMail($email, $name, $cCode)
{

	//PHPMailer Function
	$mail = new PHPMailer;
	$mail->isSMTP();
	$mail->SMTPDebug = 0;
	$mail->Debugoutput = 'html';
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 587;
	$mail->SMTPSecure = 'tls';
	$mail->SMTPAuth = true;
	$mail->Username = "mailer.nilkamal@gmail.com";
	$mail->Password = "nilkamal@123456";
	$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
	$mail->addAddress($email, $name);
	$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
	$mail->Subject = 'Please Confirm Your nilkamal Account';
	$mail->Body = "
						<p>Hi! $name </p>
						<p>Thank you for registering on our site </p>
						<br><br><br>
						<b> Please visit My Account page on site to confirm your email </b>
						<br><br>
						Your nilkamal Account Confirmation Code:&nbsp; <strong>$cCode</strong>
						<br><br>
						<b><i>Important! Please verifiy your email just after logged into the site</i></b>
						";
	if (!$mail->send()) {
		echo "<script>alert('Somthing Wrong! Please Contact Us')</script>";
	}

}


function recoverPassword()
{

	global $connF;
	global $wrongpass;

	if (isset($_POST['recoverpass'])) {

		$customerEmail = $_POST['cus_email'];

		//Google Recaptcha
		$sKey = "6LdScHYUAAAAAL6_FSP4Jgmv_Vd4-2sYytWiBt0K";
		$gResponse = $_POST['g-recaptcha-response'];
		$remoteIP = $_SERVER['REMOTE_ADDR'];
		$guRL = "s://www.google.com/recaptcha/api/siteverify?secret=$sKey&response=$gResponse&remoteip=$remoteIP";
		$retuenResponse = file_get_contents($guRL);
		$jsonResponse = json_decode($retuenResponse);

		$getCustomerSql = "SELECT * FROM customer WHERE cusEmail='$customerEmail'";
		$getCustomer = mysqli_query($connF, $getCustomerSql);
		$getCustomerRow = mysqli_fetch_array($getCustomer);
		$getCustomerCount = mysqli_num_rows($getCustomer);

		if ($getCustomerCount > 0 || $jsonResponse->success) {

			$randomPassword = generateRandomPassword();
			$encRandomPassword = md5($randomPassword);

			$setRandowPasswordSql = "UPDATE customer SET cusPassword='$encRandomPassword' WHERE cusEmail='$customerEmail'";
			$setRandowPassword = mysqli_query($connF, $setRandowPasswordSql);
			$customerName = $getCustomerRow['cusName'];


			//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($customerEmail, $customerName);
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Your nilkamal Account Password';
			$mail->Body = "
						<b> This password is generated by nilkamal Servers </b>
						<br><br>
						Your nilkamal Account Password:&nbsp; <strong>$randomPassword</strong>
						<br><br>
						<b><i>Important! Please change your password just after logged into the site</i></b>
						";
			if (!$mail->send()) {
				$wrongpass = "Somthing Wrong";
			} else {
				$wrongpass = "Password has been sent your email! Please check your inbox/spam folder";
			}
		} else {
			if (!$getCustomerCount > 0) {
				$wrongpass = "Email not found, Please check your email";
			}
			$wrongpass = "Please complete the Recaptcha!";
		}
	}


}

function setGetCookie()
{

	global $random;
	$random = rand(0, 9999999);
	if (!isset($_COOKIE['user_cookie'])) {
		setcookie('user_cookie', $random, time() + (86400), "/");//86400 = 1 day
	} else {
		return $_COOKIE['user_cookie'];
	}

}

function switchLoginLogout()
{
	if (!isset($_SESSION['cusEmail'])) {
		echo "<li><a href='register.php'>Register</a></li>";
		echo "<li><a href='login.php'>Login</a></li>";
	} else {
		echo "<li><a href='customers/myaccount.php?myorders'>My Account</a></li>";
		echo "<li><a href='logout.php'>Logout</a></li>";
	}
}

function switchLoginLogout1()
{
	if (!isset($_SESSION['cusEmail'])) {
		echo "<li class='nav-item dnone'><a href='register.php' class='nav-link'><span class='icon-user-plus' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Register</span></a></li>";
		echo "<li class='nav-item dnone'><a href='login.php' class='nav-link'><span class='icon-key' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Login</a></li>";

	} else {
		echo "
<li class='nav-item dnone'><a href='customers/myaccount.php?myorders' class='nav-link'><span class='icon-folder' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='My Account'></span><span class='dnone'>My Account</span></a></li>"
		;
		echo "<li class='nav-item dnone'><a href='logout.php' class='nav-link'>Logout</a></li>";
	}
}


function changePassword()
{

	global $connF;

	if (isset($_POST['changepassword'])) {
		$currentUser = $_SESSION['cusEmail'];
		$getCustomerPasswordSql = "SELECT * FROM customer WHERE cusEmail='$currentUser'";
		$getCustomerPassword = mysqli_query($connF, $getCustomerPasswordSql);
		$getCustomerPasswordRow = mysqli_fetch_array($getCustomerPassword);

		$currentPassword = $_POST['current_pass'];
		$newPassword = $_POST['new_pass'];
		$cNewPassword = $_POST['new_cpass'];

		$currentPasswordDB = $getCustomerPasswordRow['cusPassword'];
		$decryptCurrentPassword = md5($currentPasswordDB);

		if ($currentPassword == $decryptCurrentPassword && $newPassword == $cNewPassword) {
			$encryptNewPassword = md5($newPassword);
			$changePasswordSql = "UPDATE customer SET cusPassword='$encryptNewPassword' WHERE cusEmail = '$currentUser'";
			$changePassword = mysqli_query($connF, $changePasswordSql);
			echo "<script>alert('Password changed successfully!, Please login to contiune')</script>";
			session_destroy();
			echo "<script>window.open('../login.php','_self')</script>";
		} else if ($currentPasswordDB != $currentPassword && $newPassword == $cNewPassword) {

			echo "<script>alert('Your current password is wrong!')</script>";
		} else if ($currentPasswordDB == $currentPassword && $newPassword != $cNewPassword) {

			echo "<script>alert('Confirm password mismatch')</script>";
		} else {
			echo "<script>alert('Something wrong!')</script>";
		}

	}
}



function getAdminDetails()
{

	global $connF;

	$currentAdmin = $_SESSION['email'];
	$adminDetailsSql = "SELECT * FROM admin WHERE adminEmail ='$currentAdmin'";
	$adminDetails = mysqli_query($connF, $adminDetailsSql);
	$adminDetailsRow = mysqli_fetch_array($adminDetails);

	$adminName = $adminDetailsRow['adminName'];
	echo "$adminName";
}



//Start Add Admin Details


function addNewAdmin()
{
	global $connF;
	if (isset($_POST['addnewadmin'])) {
		$adminName = $_POST['adminName'];
		$adminEmail = $_POST['adminEmail'];
		$adminPass = $_POST['adminPass'];
		$adminCPass = $_POST['adminCPass'];
		$adminImg = $_FILES['adminimg1']['name'];
		$adminTempImg = $_FILES['adminimg1']['tmp_name'];
		$adminPno = $_POST['adminPNo'];

		if ($adminPass == $adminCPass) {
			$adminPassEnc = md5($adminPass);
			$addAdminSql = "INSERT INTO admin(adminName, adminEmail, adminPassword, adminPhoto, adminPNum) VALUES ('$adminName','$adminEmail','$adminPassEnc','$adminImg','$adminPno')";
			$addAdmin = mysqli_query($connF, $addAdminSql);
			move_uploaded_file($adminTempImg, "resources/admin_img/$adminImg");
			if ($addAdmin) {
				echo "<script>alert('Admin Added')</script>";
				echo "<script>window.open('index.php?addadmin','_self')</script>";
			}
		}
	}
}

function addTestimonials()
{
	global $connF;

	if (isset($_POST['addtestimonial'])) {
		// Collect form data and trim whitespace
		$patientname = trim($_POST['patientname']);
		$patientfeedback = trim($_POST['patientfeedback']);

		// Validate that both fields are not empty
		if (empty($patientname) || empty($patientfeedback)) {
			echo "<script>alert('Error: Both patient name and feedback are required.')</script>";
			return; // Exit the function
		}

		// Escape special characters for safe database insertion
		$patientname = mysqli_real_escape_string($connF, $patientname);
		$patientfeedback = mysqli_real_escape_string($connF, $patientfeedback);

		// SQL query
		$addTestimonialSql = "INSERT INTO testimonials (patientname, patientfeedback) VALUES ('$patientname', '$patientfeedback')";

		// Execute the query and check for errors
		if (mysqli_query($connF, $addTestimonialSql)) {
			echo "<script>alert('Patient feedback added successfully.')</script>";
			echo "<script>window.open('index.php?addtestimonial','_self')</script>";
		} else {
			// Handle query failure
			$error = mysqli_error($connF);
			echo "<script>alert('Error adding feedback: $error')</script>";
		}
	}
}
function addServices()
{
	global $connF;
	if (isset($_POST['addservice'])) {
		$servicename = trim($_POST['servicename']);
		$servicedesc = trim($_POST['servicedesc']);
		$serviceImg = $_FILES['serviceimage1']['name'];
		$serviceTempImg = $_FILES['serviceimage1']['tmp_name'];


		$addServiceSql = "INSERT INTO services(servicename,servicedesc,serviceimage)VALUES('$servicename','$servicedesc','$serviceImg')";
		$addService = mysqli_query($connF, $addServiceSql);
		move_uploaded_file($serviceTempImg, "resources/service_img/$serviceImg");

		if ($addService) {
			echo "<script>alert('Service Added')</script>";
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
	}
}

function addMedikit()
{
	global $connF;
	if (isset($_POST['addmedikit'])) {
		$kitname = trim($_POST['kitname']);
		$kitdesc = trim($_POST['kitdesc']);
		$price = trim($_POST['price']);
		$kitImg = $_FILES['kitimage1']['name'];
		$kitTempImg = $_FILES['kitimage1']['tmp_name'];


		$addMedikitsql = "INSERT INTO medikits(kitname,kitdesc,price,kitimage)VALUES('$kitname','$kitdesc','$price','$kitImg')";
		$addMedikit = mysqli_query($connF, $addMedikitsql);
		move_uploaded_file($kitTempImg, "resources/kits_img/$kitImg");

		if ($addMedikit) {
			echo "<script>alert('Medikit Added')</script>";
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		}
	}
}
function addwhyus()
{
	global $connF;
	if (isset($_POST['addwhyus'])) {
		$heading = trim($_POST['heading']);
		$description = trim($_POST['description']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		$icon = $_FILES['icon1']['name'];
		$iconTempImg = $_FILES['icon1']['tmp_name'];


		$addWhyChooseUsSql = "INSERT INTO whychooseus(heading,description,icon,aos_animation,aos_offset)VALUES('$heading','$description','$icon','$aos_animation','$aos_offset')";
		$addWhyus = mysqli_query($connF, $addWhyChooseUsSql);
		move_uploaded_file($iconTempImg, "resources/why_image/$icon");

		if ($addWhyus) {
			echo "<script>alert('whychoose us Added')</script>";
			echo "<script>window.open('index.php?addhome','_self')</script>";
		}
	}
}

function addAbout()
{
    global $connF;

    if (isset($_POST['addaboutus'])) {
        $about_desc = trim($_POST['about_desc']);
        $mission = trim($_POST['mission']);
        $vision = trim($_POST['vision']);
        $clinicImg = $_FILES['clinicimage1']['name'];
        $clinicTempImg = $_FILES['clinicimage1']['tmp_name'];

        // Validation
        if (empty($about_desc) || empty($mission) || empty($vision) || empty($clinicImg)) {
            die("<script>alert('All fields are required!')</script>");
        }

        // SQL Query
        $addAboutSql = "INSERT INTO aboutus (about_desc, mission, vision, clinic_image) 
                        VALUES ('$about_desc', '$mission', '$vision', '$clinicImg')";

        $addAbout = mysqli_query($connF, $addAboutSql);

        if ($addAbout) {
            // File Upload
            if (move_uploaded_file($clinicTempImg, "resources/about_img/$clinicImg")) {
                echo "<script>alert('About Added Successfully')</script>";
                echo "<script>window.open('index.php?addaboutus', '_self')</script>";
            } else {
                echo "<script>alert('Failed to upload image.')</script>";
            }
        } else {
            die("<script>alert('Error inserting data: " . mysqli_error($connF) . "')</script>");
        }
    }
}

function viewAbout()
{
	global $connF;

	$viewAboutSql = "SELECT * FROM aboutus";
	$viewAboutus = mysqli_query($connF, query: $viewAboutSql);

	while ($viewAboutusRow = mysqli_fetch_array(result: $viewAboutus)) {
		$aboutusId = $viewAboutusRow['id'];
		$about_desc = $viewAboutusRow['about_desc'];
		$mission = $viewAboutusRow['mission'];
		$vision = $viewAboutusRow['vision'];
		$aboutImage = $viewAboutusRow['clinic_image'];

		echo "
	      <tr>
		    <td>$aboutusId</td>
		    <td>$about_desc</td>
		    <td>$mission</td>
		    <td>$vision</td>
			<td><img src='resources/about_img/$aboutImage' style='width: 50px;height:50px;'></td>
		    <td>
			 <a href='index.php?editaboutus=$aboutusId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}


function editAbout()
{
	global $connF;
	if (isset($_POST['updateAbout'])) {
		$aboutId = $_GET['editaboutus'];
		$aboutdesc = trim($_POST['about_desc']);
		$mission = trim($_POST['mission']);
		$vision = trim($_POST['vision']);
		$newAboutImg = $_FILES['clinicimage1']['name'];
		$newAboutTempImg = $_FILES['clinicimage1']['tmp_name'];

		// Check if a new image was uploaded
		if (!empty($newAboutImg)) {
			// Fetch existing image to delete it
			$getAboutQuery = "SELECT clinic_image FROM aboutus WHERE id='$aboutId'";
			$result = mysqli_query($connF, $getAboutQuery);
			$row = mysqli_fetch_assoc($result);
			$existingImage = $row['clinic_image'];

			// Delete existing image from folder
			if (file_exists("resources/about_img/$existingImage")) {
				unlink("resources/about_img/$existingImage");
			}

			// Upload new image and update query
			move_uploaded_file($newAboutTempImg, "resources/about_img/$newAboutImg");
			$updateAboutSql = "UPDATE aboutus SET about_desc='$aboutdesc', mission='$mission', vision='$vision', clinic_image='$newAboutImg' WHERE id='$aboutId'";
		} else {
			// If no new image is uploaded, update without changing the image
			$updateAboutSql = "UPDATE aboutus SET about_desc='$aboutdesc', mission='$mission',vision='$vision' WHERE id='$aboutId'";
		}

		$updateAbout = mysqli_query($connF, $updateAboutSql);

		if ($updateAbout) {
			echo "<script>alert('About us updated')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		} else {
			echo "<script>alert('Error updating about')</script>";
		}
	}
}
function addHomeopathy()
{
    global $connF;
    if (isset($_POST['addHomeopathy'])) {
        $about_homeopathy = mysqli_real_escape_string($connF, $_POST['about_homeopathy']);

        $addHomeopathySql = "INSERT INTO homeopathy(about_homeopathy) VALUES('$about_homeopathy')";
        $addHomeopathy = mysqli_query($connF, $addHomeopathySql);

        if ($addHomeopathy) {
            echo "<script>alert('Homeopathy Details Added Successfully')</script>";
            echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
        }
    }
}
function editHomeopathy()
{
	global $conn;
	if (isset($_POST['updatehomeopathy'])) {

		// Get testimonial ID from URL
		$homeopathyId = $_GET['edithomeopathy'];

		// Sanitize input values
		$about_homeopathy = mysqli_real_escape_string($conn, $_POST['about_homeopathy']);
		
		

		// Update query
		$updateHomeopathySql = "
            UPDATE homeopathy 
            SET about_homeopathy = '$about_homeopathy'
            WHERE id = '$homeopathyId'
        ";
		$updateHomeopathy = mysqli_query($conn, $updateHomeopathySql);

	
		if ($updateHomeopathy) {
			echo "<script>alert('Homeopathy Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}
function viewHomeopathy()
{
    global $connF;

    // SQL query to get the data from the homeopathy table
    $viewHomeopathySql = "SELECT * FROM homeopathy";
    $viewHomeopathyResult = mysqli_query($connF, $viewHomeopathySql);

    while ($viewHomeopathyRow = mysqli_fetch_array($viewHomeopathyResult)) {
        $homeopathyId = $viewHomeopathyRow['id'];
        $aboutHomeopathy = $viewHomeopathyRow['about_homeopathy'];

        // Decode the JSON data
   
        // Displaying the rows in the table
        echo "
        <tr>
            <td>$homeopathyId</td>
            <td>$aboutHomeopathy</td>
            <td>
                <a href='index.php?edithomeopathy=$homeopathyId' class='btn btn-sm btn-circle btn-warning'><i class='fa fa-edit'></i></a>
            </td>
        </tr>";
    }
}



function addKeyFeatures()
{
    global $connF;
    if (isset($_POST['addkeyfeatures'])) {
        // Check current record count
        $checkSql = "SELECT COUNT(*) as total FROM key_features";
        $result = mysqli_query($connF, $checkSql);
        $row = mysqli_fetch_assoc($result);

        if ($row['total'] >= 4) {
            echo "<script>alert('You can only add up to 4 key features.')</script>";
        } else {
            $heading = trim($_POST['heading']);
            $description = trim($_POST['description']);
            $aos_animation = trim($_POST['aos_animation']);
            $aos_offset = trim($_POST['aos_offset']);

            $addkeyFeaturesSql = "INSERT INTO key_features (heading, description, aos_animation, aos_offset) VALUES ('$heading', '$description', '$aos_animation', '$aos_offset')";
            $addkeyFeatures = mysqli_query($connF, $addkeyFeaturesSql);

            if ($addkeyFeatures) {
                echo "<script>alert('Key feature added successfully.')</script>";
                echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
            }
        }
    }
}

function addHowItWorks()
{
    global $connF;
    if (isset($_POST['addhowitworks'])) {
        // Check current record count
        $checkSql = "SELECT COUNT(*) as total FROM how_it_works";
        $result = mysqli_query($connF, $checkSql);
        $row = mysqli_fetch_assoc($result);

        if ($row['total'] >= 4) {
            echo "<script>alert('You can only add up to 4 how it works records.')</script>";
        } else {
            $heading = trim($_POST['heading']);
            $description = trim($_POST['description']);
            $aos_animation = trim($_POST['aos_animation']);
            $aos_offset = trim($_POST['aos_offset']);

            $addkeyFeaturesSql = "INSERT INTO how_it_works (heading, description, aos_animation, aos_offset) VALUES ('$heading', '$description', '$aos_animation', '$aos_offset')";
            $addkeyFeatures = mysqli_query($connF, $addkeyFeaturesSql);

            if ($addkeyFeatures) {
                echo "<script>alert('How it works record added successfully.')</script>";
                echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
            }
        }
    }
}



function addSpeciality()
{
	global $connF;
	if (isset($_POST['addspeciality'])) {
		$specialityname = trim($_POST['specialityname']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		


		$addSpecialitySql = "INSERT INTO specialities(specialityname,aos_animation,aos_offset)VALUES('$specialityname','$aos_animation','$aos_offset')";
		$addSpeciality = mysqli_query($connF, $addSpecialitySql);
	
		if ($addSpeciality) {
			echo "<script>alert('Speciality Added')</script>";
			echo "<script>window.open('index.php?addspeciality','_self')</script>";
		}
	}
}
function addFAQs()
{
	global $connF;
	if (isset($_POST['addfaqs'])) {
		$question = trim(string: $_POST['question']);
		$answer = trim($_POST['answer']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		


		$addFaqSql = "INSERT INTO faqs(question,answer,aos_animation,aos_offset)VALUES('$question','$answer','$aos_animation','$aos_offset')";
		$addFaq = mysqli_query($connF, $addFaqSql);
	
		if ($addFaq) {
			echo "<script>alert('FAQ Added')</script>";
			echo "<script>window.open('index.php?addfaqs','_self')</script>";
		}
	}
}
function addWhyOurkit()
{
	global $connF;
	if (isset($_POST['addwhyourkit'])) {
		
		$answer = trim($_POST['answer']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		


		$addWhyOurkitSql = "INSERT INTO whyourkit(answer,aos_animation,aos_offset)VALUES('$answer','$aos_animation','$aos_offset')";
		$addWhyOurkit = mysqli_query($connF, $addWhyOurkitSql);
	
		if ($addWhyOurkit) {
			echo "<script>alert('Why our kit answer Added')</script>";
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		}
	}
}

function viewSpeciality()
{
	global $connF;

	$viewSpecialitySql = "SELECT * FROM specialities";
	$viewSpeciality = mysqli_query($connF, query: $viewSpecialitySql);

	while ($viewSpecialityRow = mysqli_fetch_array(result: $viewSpeciality)) {
		$specialityId = $viewSpecialityRow['id'];
		$specialityname = $viewSpecialityRow['specialityname'];
		$aos_animation = $viewSpecialityRow['aos_animation'];
		$aos_offset = $viewSpecialityRow['aos_offset'];
	

		echo "
	      <tr>
		    <td>$specialityId</td>
		    <td>$specialityname</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td><a href='index.php?deleteSpeciality=$specialityId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editspeciality=$specialityId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function viewFAQs()
{
	global $connF;

	$viewFAQSql = "SELECT * FROM faqs";
	$viewFAQ = mysqli_query($connF, query: $viewFAQSql);

	while ($viewFAQRow = mysqli_fetch_array(result: $viewFAQ)) {
		$faqId = $viewFAQRow['id'];
		$question = $viewFAQRow['question'];
		$answer = $viewFAQRow['answer'];
		$aos_animation = $viewFAQRow['aos_animation'];
		$aos_offset = $viewFAQRow['aos_offset'];
	

		echo "
	      <tr>
		    <td>$faqId</td>
		    <td>$question</td>
		    <td>$answer</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td><a href='index.php?deletefaqs=$faqId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editfaqs=$faqId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function viewKeyFeatures()
{
	global $connF;

	$viewKeyFeaturesSql = "SELECT * FROM key_features";
	$keyFeatures = mysqli_query($connF, query: $viewKeyFeaturesSql);

	while ($keyFeaturesRow = mysqli_fetch_array(result: $keyFeatures)) {
		$faqId = $keyFeaturesRow['id'];
		$heading = $keyFeaturesRow['heading'];
		$description = $keyFeaturesRow['description'];
		$aos_animation = $keyFeaturesRow['aos_animation'];
		$aos_offset = $keyFeaturesRow['aos_offset'];
	

		echo "
	      <tr>
		    <td>$faqId</td>
		    <td>$heading</td>
		    <td>$description</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td>
			 <a href='index.php?editkeyfeatures=$faqId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}

function viewWhyOurkit()
{
	global $connF;

	$viewKeyFeaturesSql = "SELECT * FROM whyourkit";
	$keyFeatures = mysqli_query($connF, query: $viewKeyFeaturesSql);

	while ($keyFeaturesRow = mysqli_fetch_array(result: $keyFeatures)) {
		$faqId = $keyFeaturesRow['id'];
		$answer = $keyFeaturesRow['answer'];
		$aos_animation = $keyFeaturesRow['aos_animation'];
		$aos_offset = $keyFeaturesRow['aos_offset'];
	

		echo "
	      <tr>
		    <td>$faqId</td>
		    <td>$answer</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td>
			<a href='index.php?deletewhyourkit=$faqId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editwhyourkit=$faqId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function viewHowitWorks()
{
	global $connF;

	$viewKeyFeaturesSql = "SELECT * FROM how_it_works";
	$keyFeatures = mysqli_query($connF, query: $viewKeyFeaturesSql);

	while ($keyFeaturesRow = mysqli_fetch_array(result: $keyFeatures)) {
		$faqId = $keyFeaturesRow['id'];
		$heading = $keyFeaturesRow['heading'];
		$description = $keyFeaturesRow['description'];
		$aos_animation = $keyFeaturesRow['aos_animation'];
		$aos_offset = $keyFeaturesRow['aos_offset'];
	

		echo "
	      <tr>
		    <td>$faqId</td>
		    <td>$heading</td>
		    <td>$description</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td>
			 <a href='index.php?edithowitworks=$faqId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}

function viewServices()
{
	global $connF;

	$viewServicesSql = "SELECT * FROM services";
	$viewServices = mysqli_query($connF, query: $viewServicesSql);

	while ($viewServicesRow = mysqli_fetch_array(result: $viewServices)) {
		$serviceId = $viewServicesRow['id'];
		$servicename = $viewServicesRow['servicename'];
		$servicedesc = $viewServicesRow['servicedesc'];
		$aos_animation = $viewServicesRow['aos_animation'];
		$aos_offset = $viewServicesRow['aos_offset'];
		$servieimg = $viewServicesRow['serviceimage'];

		echo "
	      <tr>
		    <td>$serviceId</td>
		    <td>$servicename</td>
		    <td>$servicedesc</td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
			<td><img src='resources/service_img/$servieimg' style='width: 50px;height:50px;'></td>
		    <td><a href='index.php?deleteService=$serviceId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editService=$serviceId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function viewMedikits()
{
	global $connF;

	$viewMedikitSql = "SELECT * FROM medikits";
	$viewMedikit = mysqli_query($connF, query: $viewMedikitSql);

	while ($viewMedikitRow = mysqli_fetch_array(result: $viewMedikit)) {
		$medikitId = $viewMedikitRow['id'];
		$kitname = $viewMedikitRow['kitname'];
		$kitdesc = $viewMedikitRow['kitdesc'];
		$price = $viewMedikitRow['price'];
		$kitimg = $viewMedikitRow['kitimage'];

		echo "
	      <tr>
		    <td>$medikitId</td>
		    <td>$kitname</td>
		    <td>$kitdesc</td>
		    <td>$price</td>
			<td><img src='resources/kits_img/$kitimg' style='width: 50px;height:50px;'></td>
		    <td><a href='index.php?deletemedikit=$medikitId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editmedikit=$medikitId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function viewWhyUs()
{
	global $connF;

	$viewWhyUsSql = "SELECT * FROM whychooseus";
	$viewWhyUs = mysqli_query($connF, query: $viewWhyUsSql);

	while ($viewWhyUsRow = mysqli_fetch_array(result: $viewWhyUs)) {
		$whyusId = $viewWhyUsRow['id'];
		$heading = $viewWhyUsRow['heading'];
		$description = $viewWhyUsRow['description'];
		$aos_animation = $viewWhyUsRow['aos_animation'];
		$aos_offset = $viewWhyUsRow['aos_offset'];
		$icon = $viewWhyUsRow['icon'];

		echo "
	      <tr>
		    <td>$whyusId</td>
		    <td>$heading</td>
		    <td>$description</td>
			<td><img src='resources/why_image/$icon' style='width: 50px;height:50px;'></td>
		    <td>$aos_animation</td>
		    <td>$aos_offset</td>
		    <td><a href='index.php?deletewhyus=$whyusId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editwhyus=$whyusId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}
function editServices()
{
	global $connF;
	if (isset($_POST['updateService'])) {
		$serviceId = $_GET['editService'];
		$servicename = trim($_POST['servicename']);
		$servicedesc = trim($_POST['servicedesc']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		$newServiceImg = $_FILES['serviceimage1']['name'];
		$newServiceTempImg = $_FILES['serviceimage1']['tmp_name'];

		// Check if a new image was uploaded
		if (!empty($newServiceImg)) {
			// Fetch existing image to delete it
			$getServiceQuery = "SELECT serviceimage FROM services WHERE id='$serviceId'";
			$result = mysqli_query($connF, $getServiceQuery);
			$row = mysqli_fetch_assoc($result);
			$existingImage = $row['serviceimage'];

			// Delete existing image from folder
			if (file_exists("resources/service_img/$existingImage")) {
				unlink("resources/service_img/$existingImage");
			}

			// Upload new image and update query
			move_uploaded_file($newServiceTempImg, "resources/service_img/$newServiceImg");
			$updateServiceSql = "UPDATE services SET servicename='$servicename', servicedesc='$servicedesc', aos_animation='$aos_animation',aos_offset='$aos_offset', serviceimage='$newServiceImg' WHERE id='$serviceId'";
		} else {
			// If no new image is uploaded, update without changing the image
			$updateServiceSql = "UPDATE services SET servicename='$servicename', servicedesc='$servicedesc',aos_animation='$aos_animation',aos_offset='$aos_offset' WHERE id='$serviceId'";
		}

		$updateService = mysqli_query($connF, $updateServiceSql);

		if ($updateService) {
			echo "<script>alert('Service updated')</script>";
			echo "<script>window.open('index.php?addservices','_self')</script>";
		} else {
			echo "<script>alert('Error updating service')</script>";
		}
	}
}
function editMedikit()
{
	global $connF;
	if (isset($_POST['updatemedikit'])) {
		$medikitId = $_GET['editmedikit'];
		$kitname = trim($_POST['kitname']);
		$kitdesc = trim($_POST['kitdesc']);
		$price = trim($_POST['price']);
		$newkitImg = $_FILES['kitimage1']['name'];
		$newkitTempImg = $_FILES['kitimage1']['tmp_name'];

		// Check if a new image was uploaded
		if (!empty($newkitImg)) {
			// Fetch existing image to delete it
			$getKitsQuery = "SELECT kitimage FROM medikits WHERE id='$medikitId'";
			$result = mysqli_query($connF, $getKitsQuery);
			$row = mysqli_fetch_assoc($result);
			$existingImage = $row['kitimage'];

			// Delete existing image from folder
			if (file_exists("resources/kits_img/$existingImage")) {
				unlink("resources/kits_img/$existingImage");
			}

			// Upload new image and update query
			move_uploaded_file($newkitTempImg, "resources/kits_img/$newkitImg");
			$updateKitSql = "UPDATE medikits SET kitname='$kitname', kitdesc='$kitdesc', price='$price', kitimage='$newkitImg' WHERE id='$medikitId'";
		} else {
			// If no new image is uploaded, update without changing the image
			$updateKitSql = "UPDATE medikits SET kitname='$kitname', kitdesc='$kitdesc',price='$price' WHERE id='$medikitId'";
		}

		$updateKit = mysqli_query($connF, $updateKitSql);

		if ($updateKit) {
			echo "<script>alert('medikit updated')</script>";
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		} else {
			echo "<script>alert('Error updating medikit')</script>";
		}
	}
}
function editWhyChooseUs()
{
	global $connF;
	if (isset($_POST['updateWhyus'])) {
		$whyusId = $_GET['editwhyus'];
		$heading = trim($_POST['heading']);
		$description = trim($_POST['description']);
		$aos_animation = trim($_POST['aos_animation']);
		$aos_offset = trim($_POST['aos_offset']);
		$newicon = $_FILES['icon1']['name'];
		$newiconTempImg = $_FILES['icon1']['tmp_name'];

		// Check if a new image was uploaded
		if (!empty($newicon)) {
			// Fetch existing image to delete it
			$getWhyUsQuery = "SELECT icon FROM whychooseus WHERE id='$whyusId'";
			$result = mysqli_query($connF, $getWhyUsQuery);
			$row = mysqli_fetch_assoc($result);
			$existingImage = $row['icon'];

			// Delete existing image from folder
			if (file_exists("resources/why_image/$existingImage")) {
				unlink("resources/why_image/$existingImage");
			}

			// Upload new image and update query
			move_uploaded_file($newiconTempImg, "resources/why_image/$newicon");
			$updateWhyusSql = "UPDATE whychooseus SET heading='$heading', description='$description', aos_animation='$aos_animation',aos_offset='$aos_offset', icon='$newicon' WHERE id='$whyusId'";
		} else {
			// If no new image is uploaded, update without changing the image
			$updateWhyusSql = "UPDATE whychooseus SET heading='$heading', description='$description', aos_animation='$aos_animation',aos_offset='$aos_offset' WHERE id='$whyusId'";
		}

		$updateWhyus = mysqli_query($connF, $updateWhyusSql);

		if ($updateWhyus) {
			echo "<script>alert('why us updated')</script>";
			echo "<script>window.open('index.php?addhome','_self')</script>";
		} else {
			echo "<script>alert('Error updating why us')</script>";
		}
	}
}
function deleteServices()
{
	global $connF;
	if (isset($_GET['deleteService'])) {

		$serviceId = $_GET['deleteService'];
		$deleteServiceSql = "DELETE FROM services WHERE id='$serviceId'";
		$deleteService = mysqli_query($connF, $deleteServiceSql);
		if ($deleteService) {
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
	}

}
function deleteWhyUs()
{
	global $connF;
	if (isset($_GET['deletewhyus'])) {

		$whyusId = $_GET['deletewhyus'];
		$deleteWhySql = "DELETE FROM whychooseus WHERE id='$whyusId'";
		$deletewhyus = mysqli_query($connF, $deleteWhySql);
		if ($deletewhyus) {
			echo "<script>window.open('index.php?addhome','_self')</script>";
		}
	}

}
function deleteWhyOurkit()
{
	global $connF;
	if (isset($_GET['deletewhyourkit'])) {

		$whyourkitId = $_GET['deletewhyourkit'];
		$whyourkitSql = "DELETE FROM whyourkit WHERE id='$whyourkitId'";
		$deletewhyus = mysqli_query($connF, $whyourkitSql);
		if ($deletewhyus) {
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		}
	}

}
function deleteMedikit()
{
	global $connF;
	if (isset($_GET['deletemedikit'])) {

		$medikitId = $_GET['deletemedikit'];
		$medikitSql = "DELETE FROM medikits WHERE id='$medikitId'";
		$deletewhyus = mysqli_query($connF, $medikitSql);
		if ($deletewhyus) {
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		}
	}

}
function deleteSpeciality()
{
	global $connF;
	if (isset($_GET['deleteSpeciality'])) {

		$specialityId = $_GET['deleteSpeciality'];
		$deleteSpecialitySql = "DELETE FROM specialities WHERE id='$specialityId'";
		$deleteSpeciality = mysqli_query($connF, $deleteSpecialitySql);
		if ($deleteSpeciality) {
			echo "<script>window.open('index.php?addspeciality','_self')</script>";
		}
	}

}
function deleteFAQ()
{
	global $connF;
	if (isset($_GET['deletefaqs'])) {

		$faqId = $_GET['deletefaqs'];
		$deletefaqSql = "DELETE FROM faqs WHERE id='$faqId'";
		$deletefaq = mysqli_query($connF, $deletefaqSql);
		if ($deletefaq) {
			echo "<script>window.open('index.php?addfaqs','_self')</script>";
		}
	}

}
function editTestimonials()
{
	global $conn;
	if (isset($_POST['updateTestimonial'])) {

		// Get testimonial ID from URL
		$testimonialId = $_GET['editTestimonial'];

		// Sanitize input values
		$patientName = mysqli_real_escape_string($conn, $_POST['patientname']);
		$patientFeedback = mysqli_real_escape_string($conn, $_POST['patientfeedback']);

		// Update query
		$updateTestimonialSql = "
            UPDATE testimonials 
            SET patientname = '$patientName', 
                patientfeedback = '$patientFeedback' 
            WHERE id = '$testimonialId'
        ";
		$updateTestimonial = mysqli_query($conn, $updateTestimonialSql);

		// Check if update was successful
		if ($updateTestimonial) {
			echo "<script>alert('Testimonial Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addtestimonial','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}
function editSpecialities()
{
	global $conn;
	if (isset($_POST['updatespeciality'])) {

		// Get testimonial ID from URL
		$specialityId = $_GET['editspeciality'];

		// Sanitize input values
		$specialityname = mysqli_real_escape_string($conn, $_POST['specialityname']);
		$aos_animation = mysqli_real_escape_string($conn, $_POST['aos_animation']);
		$aos_offset = mysqli_real_escape_string($conn, $_POST['aos_offset']);
		

		// Update query
		$updateSpecialitySql = "
            UPDATE specialities 
            SET specialityname = '$specialityname',
			aos_animation = '$aos_animation',
			aos_offset = '$aos_offset'
            WHERE id = '$specialityId'
        ";
		$updateSpeciality = mysqli_query($conn, $updateSpecialitySql);

		// Check if update was successful
		if ($updateSpeciality) {
			echo "<script>alert('Speciality Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addspeciality','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}
function editFAQs()
{
	global $conn;
	if (isset($_POST['updatefaqs'])) {

		// Get testimonial ID from URL
		$faqId = $_GET['editfaqs'];

		// Sanitize input values
		$question = mysqli_real_escape_string($conn, $_POST['question']);
		$answer = mysqli_real_escape_string($conn, $_POST['answer']);
		$aos_animation = mysqli_real_escape_string($conn, $_POST['aos_animation']);
		$aos_offset = mysqli_real_escape_string($conn, $_POST['aos_offset']);
		

		// Update query
		$updateFAQSql = "
            UPDATE faqs 
            SET question = '$question',answer ='$answer',aos_animation ='$aos_animation',aos_offset='$aos_offset'
            WHERE id = '$faqId'
        ";
		$updateFAQ = mysqli_query($conn, $updateFAQSql);

		// Check if update was successful
		if ($updateFAQ) {
			echo "<script>alert('FAQ Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addfaqs','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}
function editKeyFeatures()
{
	global $conn;
	if (isset($_POST['updateKeyFeature'])) {

		// Get testimonial ID from URL
		$faqId = $_GET['editkeyfeatures'];

		// Sanitize input values
		$heading = mysqli_real_escape_string($conn, $_POST['heading']);
		$description = mysqli_real_escape_string($conn, $_POST['description']);
		$aos_animation = mysqli_real_escape_string($conn, $_POST['aos_animation']);
		$aos_offset = mysqli_real_escape_string($conn, $_POST['aos_offset']);
		

		// Update query
		$updateKeyFeatureSql = "
            UPDATE key_features 
            SET heading = '$heading',description ='$description',aos_animation ='$aos_animation',aos_offset='$aos_offset'
            WHERE id = '$faqId'
        ";
		$updateKeyFeature = mysqli_query($conn, $updateKeyFeatureSql);

		// Check if update was successful
		if ($updateKeyFeature) {
			echo "<script>alert('Key feature Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}
function editHowitworks()
{
	global $conn;
	if (isset($_POST['updatehowitworks'])) {

		// Get testimonial ID from URL
		$faqId = $_GET['edithowitworks'];

		// Sanitize input values
		$heading = mysqli_real_escape_string($conn, $_POST['heading']);
		$description = mysqli_real_escape_string($conn, $_POST['description']);
		$aos_animation = mysqli_real_escape_string($conn, $_POST['aos_animation']);
		$aos_offset = mysqli_real_escape_string($conn, $_POST['aos_offset']);
		

		// Update query
		$updateKeyFeatureSql = "
            UPDATE how_it_works 
            SET heading = '$heading',description ='$description',aos_animation ='$aos_animation',aos_offset='$aos_offset'
            WHERE id = '$faqId'
        ";
		$updateKeyFeature = mysqli_query($conn, $updateKeyFeatureSql);

		// Check if update was successful
		if ($updateKeyFeature) {
			echo "<script>alert('How it works Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addhomeopathy','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}

function editWhyourkit()
{
	global $conn;
	if (isset($_POST['updatewhyourkit'])) {

		// Get testimonial ID from URL
		$faqId = $_GET['editwhyourkit'];

		// Sanitize input values
		$answer = mysqli_real_escape_string($conn, $_POST['answer']);
		$aos_animation = mysqli_real_escape_string($conn, $_POST['aos_animation']);
		$aos_offset = mysqli_real_escape_string($conn, $_POST['aos_offset']);
		

		// Update query
		$updateWhyourKitSql = "
            UPDATE whyourkit 
            SET answer = '$answer',aos_animation ='$aos_animation',aos_offset='$aos_offset'
            WHERE id = '$faqId'
        ";
		$updateWhyourKit = mysqli_query($conn, $updateWhyourKitSql);

		// Check if update was successful
		if ($updateWhyourKit) {
			echo "<script>alert('Why our kit Updated Successfully!')</script>";
			echo "<script>window.open('index.php?addaboutkit','_self')</script>";
		} else {
			// Output the error for debugging
			$error = mysqli_error($conn);
			echo "<script>alert('Something went wrong! Error: $error')</script>";
		}
	}
}


// function addSuperAdmin() {
// 	global $connF;
// 	if(isset($_POST['addnewadmin'])){
// 		$adminName = $_POST['adminName'];
// 		$adminEmail = $_POST['adminEmail'];
// 		$adminPass = $_POST['adminPass'];
// 		$adminCPass = $_POST['adminCPass'];
// 		$adminImg = $_FILES['adminimg1']['name'];
// 		$adminTempImg = $_FILES['adminimg1']['tmp_name'];
// 		$adminPno = $_POST['adminPNo'];

// 		if($adminPass == $adminCPass){
// 			$adminPassEnc = md5($adminPass);
// 			$addAdminSql = "INSERT INTO superadmin(adminName, adminEmail, adminPassword, adminPhoto, adminPNum) VALUES ('$adminName','$adminEmail','$adminPassEnc','$adminImg','$adminPno')";
// 			$addAdmin = mysqli_query($connF,$addAdminSql);
// 			move_uploaded_file($adminTempImg,"resources/admin_img/$adminImg");
// 			if($addAdmin){
// 			echo "<script>alert('Admin Added')</script>";
// 			echo "<script>window.open('index.php?addadmin','_self')</script>";
// 		}
// 		}
// 	}
// }

function addSuperAdmin()
{
	global $connF;

	if (isset($_POST['addsuperadmin'])) {
		$adminName = $_POST['adminName'];
		$adminEmail = $_POST['adminEmail'];
		$adminPass = $_POST['adminPass'];
		$adminCPass = $_POST['adminCPass'];
		$adminImg = $_FILES['adminimg1']['name'];
		$adminTempImg = $_FILES['adminimg1']['tmp_name'];
		$adminPno = $_POST['adminPNo'];

		// check for passswords match
		if ($adminPass !== $adminCPass) {
			echo "<script>alert('passwords do not match..please try again')</script>";
			return;
		}

		// check for email exists

		$checkemailexists = "SELECT * FROM superadmin WHERE adminEmail ='$adminEmail'";
		$checkResult = mysqli_query($connF, $checkemailexists);

		if (mysqli_num_rows($checkResult) > 0) {
			$superadmin = mysqli_fetch_assoc($checkResult);

			if ($superadmin['status'] === 'rejected') {
				echo "<script>alert('Registration failed...this email is  rejected by superadmin and cannot be used again')</script>";
				return;
			} elseif ($superadmin['status'] === 'approved' || $superadmin['status'] === 'pending') {
				echo "<script>alert('this email is already in use..please register with another email')</script>";
				return;
			}
		}

		// encrypt password

		$superadminPassEnc = md5($adminPass);

		$addSuperAdminSql = "INSERT INTO superadmin(adminName, adminEmail, adminPassword, adminPhoto, adminPNum, status)
		                   VALUES('$adminName', '$adminEmail', '$superadminPassEnc', '$adminImg', '$adminPno', 'pending')";


		$addSuperAdmin = mysqli_query($connF, $addSuperAdminSql);

		if ($addSuperAdmin) {
			move_uploaded_file($adminTempImg, "resources/admin_img/$adminImg");
			echo "<script>alert('Registration successfull....your account is pending for approval')</script>";
			echo "<script>window.open('login.php', '_self');</script>";
		} else {
			echo "<script>alert('Failed to register. Please try again later.');</script>";
		}

	}
}

// Start Admin View

function viewAdmin()
{
	global $connF;
	$viewAdminSql = "SELECT * FROM admin WHERE 1";
	$viewAdmin = mysqli_query($connF, $viewAdminSql);

	while ($viewAdminRow = mysqli_fetch_array($viewAdmin)) {
		$adminId = $viewAdminRow['adminId'];
		$adminName = $viewAdminRow['adminName'];
		$adminEmail = $viewAdminRow['adminEmail'];
		$adminPass = $viewAdminRow['adminPassword'];
		$adminPassDec = md5($adminPass);
		$adminImg = $viewAdminRow['adminPhoto'];
		$adminPno = $viewAdminRow['adminPNum'];

		echo "	
				<tr>
					<td>$adminId</td>
					<td>$adminName</td>
					<td>$adminEmail</td>
					<td>$adminPassDec</td>
					<td><img src='resources/admin_img/$adminImg' style='width: 50px;height:50px;'></td>
					<td>$adminPno</td>
					<td><a href='index.php?deleteAdmin=$adminId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
				</tr>
		
			";
	}
}
function viewAllApprovedSuperAdmin()
{
	global $connF;
	$viewAdminSql = "SELECT * FROM superadmin WHERE status='approved'";
	$viewAdmin = mysqli_query($connF, $viewAdminSql);

	while ($viewAdminRow = mysqli_fetch_array($viewAdmin)) {

		$adminName = $viewAdminRow['adminName'];
		$adminEmail = $viewAdminRow['adminEmail'];
		$adminImg = $viewAdminRow['adminPhoto'];
		$adminPno = $viewAdminRow['adminPNum'];
		$adminStatus = $viewAdminRow['status'];
		echo "	
				<tr>
					<td>$adminName</td>
					<td>$adminEmail</td>
					<td><img src='resources/admin_img/$adminImg' style='width: 50px;height:50px;'></td>
					<td>$adminPno</td>
					<td class='text-success'>$adminStatus</td>
					
				</tr>
		
			";
	}
}

function deleteAppointment()
{
	global $connF;
	if (isset($_GET['deleteAppointment'])) {
		$appointmentId = $_GET['deleteAppointment'];
		$deleteAdminSql = "DELETE FROM appointments WHERE id='$appointmentId'";
		$deleteAppointment = mysqli_query($connF, $deleteAdminSql);
		if ($deleteAppointment) {
			echo "<script>alert('Appointment Deleted Sucessfully')</script>";
			echo "<script>window.open('index.php?appointment','_self')</script>";
		}
	}
}
function deleteTestimonial()
{
	global $connF;
	if (isset($_GET['deleteTestimonial'])) {
		$testimonialId = $_GET['deleteTestimonial'];
		$deleteTestimonialSql = "DELETE FROM testimonials WHERE id='$testimonialId'";
		$deleteTestimonial = mysqli_query($connF, $deleteTestimonialSql);
		if ($deleteTestimonial) {
			echo "<script>alert('Testimonial Deleted Sucessfully')</script>";
			echo "<script>window.open('index.php?addtestimonial','_self')</script>";
		}
	}
}
function viewBookedAppointments()
{
	global $connF;
	$viewAptsql = "SELECT * FROM appointments";
	$viewApt = mysqli_query($connF, $viewAptsql);


	while ($viewAptRow = mysqli_fetch_array($viewApt)) {
		$appointmentId = $viewAptRow['id'];
		$firstname = $viewAptRow['firstname'];
		$lastname = $viewAptRow['lastname'];
		$gender = $viewAptRow['gender'];
		$email = $viewAptRow['email'];
		$age = $viewAptRow['age'];
		$mobile = $viewAptRow['mobile'];

		echo "
    <tr>
        <td>" . $firstname . " " . $lastname . "</td>
        <td>" . $gender . "</td>
        <td>" . $email . "</td>
        <td>" . $mobile . "</td>
        <td>" . $age . "</td>
		<td><a href='index.php?deleteAppointment=$appointmentId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
    </tr>
";

	}
}

function viewTestimonials()
{
	global $connF;

	$viewTestiSql = "SELECT * FROM testimonials";
	$viewTesti = mysqli_query($connF, query: $viewTestiSql);

	while ($viewTestiRow = mysqli_fetch_array(result: $viewTesti)) {
		$testimonialId = $viewTestiRow['id'];
		$patientname = $viewTestiRow['patientname'];
		$patientfeedback = $viewTestiRow['patientfeedback'];

		echo "
	      <tr>
		    <td>$testimonialId</td>
		    <td>$patientname</td>
		    <td>$patientfeedback</td>
		    <td><a href='index.php?deleteTestimonial=$testimonialId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a>
			 <a href='index.php?editTestimonial=$testimonialId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
			</td>
			
		 </tr>  
	   ";
	}
}



function viewSuperAdmin()
{
	global $connF;

	$viewSuperAdminsql = "SELECT * FROM superadmin WHERE status = 'pending'";
	$viewSuperAdmin = mysqli_query($connF, $viewSuperAdminsql);
	while ($viewSuperAdminRow = mysqli_fetch_array($viewSuperAdmin)) {
		$adminId = $viewSuperAdminRow['adminId'];
		$adminName = $viewSuperAdminRow['adminName'];
		$adminEmail = $viewSuperAdminRow['adminEmail'];
		$adminImg = $viewSuperAdminRow['adminPhoto'];
		$adminPno = $viewSuperAdminRow['adminPNum'];
		$adminStatus = $viewSuperAdminRow['status'];

		echo "
		<tr>
                <td>$adminName</td>
                <td>$adminEmail</td>
                <td><img src='resources/admin_img/$adminImg' style='width: 50px;height:50px;'></td>
                <td>$adminPno</td>
                <td class='text-warning'>$adminStatus</td>
                <td>
                    <a href='index.php?approveAdmin=$adminId' class='btn btn-sm btn-success'>Approve <i class='mdi mdi-check'></i></a>
                    <a href='index.php?rejectAdmin=$adminId' class='btn btn-sm btn-danger'>Reject <i class='mdi mdi-close'></i></a>
                </td>
            </tr>
		";
	}
}

// End View Admin

// Start Delete Admin

function deleteAdmin()
{
	global $connF;
	if (isset($_GET['deleteAdmin'])) {
		$adminId = $_GET['deleteAdmin'];
		$deleteAdminSql = "DELETE FROM admin WHERE adminId='$adminId'";
		$deleteAdmin = mysqli_query($connF, $deleteAdminSql);
		if ($deleteAdmin) {
			echo "<script>alert('Admin Deleted')</script>";
			echo "<script>window.open('index.php?addadmin','_self')</script>";
		}
	}
}
// End Delete Admin
// Start Add About Us


// End Add About Us

// Start Edit About Us
function updateAbout()
{

	global $connF;

	if (isset($_POST['editabout'])) {

		$aboutusId = $_GET['editabout'];

		$getAboutSql = "SELECT * FROM aboutus WHERE aboutusId='$aboutusId'";
		$getAbout = mysqli_query($connF, $getAboutSql);
		$getAboutRow = mysqli_fetch_array($getAbout);

		$aboutDesc = $_POST['aboutDesc'];
		$projectImg = $_FILES['projectImg']['name'];

		$aboutMission = $_POST['aboutMission'];
		$aboutValues = $_POST['aboutValues'];
		$aboutVision = $_POST['aboutVision'];


		$updateAboutSql = "UPDATE aboutus SET aboutDesc='$aboutDesc',aboutVision='$aboutVision',aboutMission='$aboutMission',aboutValues ='$aboutValues' WHERE aboutusId='$aboutusId'";
		$updateAbout = mysqli_query($connF, $updateAboutSql);
		if ($updateAbout) {
			echo "<script>alert('About us Updated')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		} else {
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
	}
}
// End Edit About Us

//Start View About Us
function displayAbout()
{
	global $connF;
	$getAboutSql = "SELECT * FROM aboutus WHERE 1";
	$getAbout = mysqli_query($connF, $getAboutSql);
	while ($getAboutRow = mysqli_fetch_array($getAbout)) {
		$aboutusId = $getAboutRow['aboutusId'];
		$aboutDesc = $getAboutRow['aboutDesc'];
		$aboutVision = $getAboutRow['aboutVision'];
		$aboutMission = $getAboutRow['aboutMission'];
		$aboutValues = $getAboutRow['aboutValues'];


		echo "
			<tr>
				<td>$aboutusId</td>
				<td>$aboutDesc</td>
				<td>$aboutVision</td>
				<td>$aboutMission</td>
				<td>$aboutValues</td>
			
				<td><a href='index.php?editabout=$aboutusId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
		// <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteAboutUs=$aboutusId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

	}
}

// End View About Us 

// Start Delete About Us
function deleteAboutUs()
{
	global $connF;
	if (isset($_GET['deleteAboutUs'])) {

		$AboutId = $_GET['deleteAboutUs'];
		$deleteAboutUsSql = "DELETE FROM aboutus WHERE aboutusId='$AboutId'";
		$deleteAboutUs = mysqli_query($connF, $deleteAboutUsSql);
		if ($deleteAboutUs) {
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
	}

}


// Start Add Project Category

function addProjectCategory()
{
	global $connF;
	if (isset($_POST['addnewprojectcategory'])) {

		$projectCatName = $_POST['projectCatName'];

		// Check if the file has been uploaded
		if (isset($_FILES['projectCatImg']) && $_FILES['projectCatImg']['error'] === UPLOAD_ERR_OK) {
			$projectCatImg = $_FILES['projectCatImg']['name'];
			$tempImg1 = $_FILES['projectCatImg']['tmp_name'];

			// Move the uploaded file
			if (move_uploaded_file($tempImg1, "resources/projectcategory_img/$projectCatImg")) {

				// Insert the data into the database
				$addProjectCatSql = "INSERT INTO projectcategory(projectCatName, projectCatImg) VALUES ('$projectCatName','$projectCatImg')";
				$addProjectCat = mysqli_query($connF, $addProjectCatSql);

				if ($addProjectCat) {
					echo "<script>alert('Project Category Added')</script>";
					echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
				} else {
					echo "<script>alert('Database error: Project Category not added')</script>";
				}
			} else {
				echo "<script>alert('Failed to upload the image.')</script>";
			}
		} else {
			echo "<script>alert('No file uploaded or file upload error.')</script>";
		}
	}
}

// End Add Project Category

// Start View Project Category


function ViewProjectCat()
{
	global $connF;
	$getProjectCatSql = "SELECT * FROM projectcategory WHERE 1";
	$getProjectCat = mysqli_query($connF, $getProjectCatSql);
	while ($getProjectCatRow = mysqli_fetch_array($getProjectCat)) {

		$projectCatId = $getProjectCatRow['projectCatId'];
		$projectCatImg = $getProjectCatRow['projectCatImg'];
		$projectCatName = $getProjectCatRow['projectCatName'];

		echo "
			<tr>
				<td>$projectCatId</td>
				<td>$projectCatName</td>
                
				<td><img src='resources/projectcategory_img/$projectCatImg' style='width: 50px;height:50px;'></td>
				";
		echo "
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProjectCat=$projectCatId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editprojectcategory=$projectCatId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
// End View Project Category

// Start Edit Project Category
function editprojectcat()
{
	global $connF;

	if (isset($_POST['editprojectcat'])) {
		$projectCatId = $_GET['editprojectcategory'];

		$getprojectCatSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCat = mysqli_query($connF, $getprojectCatSql);
		$getprojectCatRow = mysqli_fetch_array($getprojectCat);

		$projectCatName = $_POST['projectCatName'];
		$projectCatImg = $_POST['projectCatImg'];
		$projectCatImgOld = $getprojectCatRow['projectCatImg'];

		$projectCatImg = $_FILES['projectCatImg']['name'];

		if (empty($projectCatImg)) {
			$projectCatImg = $projectCatImgOld;
		}
		$tempImg1 = $_FILES['projectCatImg']['tmp_name'];
		move_uploaded_file($tempImg1, "resources/projectcategory_img/$projectCatImg");

		$updateProjectCatSql = "UPDATE projectcategory SET projectCatName='$projectCatName', projectCatImg='$projectCatImg' WHERE projectCatId='$projectCatId'";
		$updateProjectCat = mysqli_query($connF, $updateProjectCatSql);

		if ($updateProjectCat) {
			echo "<script>alert('Project Updated');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		} else {
			echo "<script>alert('Something went wrong!');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		}
	}
}

// End Edit Project Category

// Start Delete Project Category

function deleteProjectCat()
{
	global $connF;
	if (isset($_GET['deleteProjectCat'])) {

		$projectCatId = $_GET['deleteProjectCat'];
		$deleteProjectCatSql = "DELETE FROM  projectcategory WHERE projectCatId='$projectCatId'";
		$deleteProjectCat = mysqli_query($connF, $deleteProjectCatSql);
		if ($deleteProjectCat) {
			echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
		}
	}

}
// End Project Category

// Start Add Project
function addProject()
{
	global $connF;
	if (isset($_POST['addnewproject'])) {

		$projectName = $_POST['projectName'];
		$projectCatId = $_POST['projectCatId'];
		$projectstatusId = $_POST['projectstatusId'];
		$projectDesc = $_POST['projectDesc'];
		$projectLoc = $_POST['projectLoc'];
		$projectDate = $_POST['projectDate'];
		$projectImg = $_FILES['projectImg']['name'];
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1, "resources/project_img/$projectImg");

		$addProjectSql = "INSERT INTO project(projectName,projectImg,projectDesc,projectLoc,projectDate,projectCatId,projectstatusId) VALUES ('$projectName','$projectImg','$projectDesc','$projectLoc','$projectDate','$projectCatId','$projectstatusId')";
		$addProject = mysqli_query($connF, $addProjectSql);
		if ($addProject) {
			echo "<script>alert('Project Added')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}

	}
}

// End Add Project

// Start Edit Project
function updateProject()
{

	global $connF;

	if (isset($_POST['editproject'])) {

		$projectId = $_GET['editproject'];

		$getProjectSql = "SELECT * FROM project WHERE projectId='$projectId'";
		$getProject = mysqli_query($connF, $getProjectSql);
		$getProjectRow = mysqli_fetch_array($getProject);

		$projectName = $_POST['projectName'];
		$projectImg = $_FILES['projectImg']['name'];

		$projectDesc = $_POST['projectDesc'];
		$projectLoc = $_POST['projectLoc'];
		$projectCatId = $_POST['projectCatId'];
		$projectstatusId = $_POST['projectstatusId'];
		$projectImgOld = $getProjectRow['projectImg'];


		if (empty($projectImg)) {
			$projectImg = $projectImgOld;
		}
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1, "resources/project_img/$projectImg");

		$updateProjectSql = "UPDATE project SET projectName='$projectName',projectImg='$projectImg',projectDesc='$projectDesc',projectLoc ='$projectLoc',projectCatId='$projectCatId',projectstatusId='$projectstatusId' WHERE projectId='$projectId'";
		$updateProject = mysqli_query($connF, $updateProjectSql);
		if ($updateProject) {
			echo "<script>alert('Project Updated')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		} else {
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	}
}
// End Edit Project

//Start View Project
function displayProject()
{
	global $connF;
	$getProjectSql = "SELECT * FROM project WHERE 1";
	$getProject = mysqli_query($connF, $getProjectSql);
	while ($getProjectRow = mysqli_fetch_array($getProject)) {
		$projectId = $getProjectRow['projectId'];
		$projectName = $getProjectRow['projectName'];
		$projectImg = $getProjectRow['projectImg'];
		$projectDesc = $getProjectRow['projectDesc'];
		$projectLoc = $getProjectRow['projectLoc'];
		$projectDate = $getProjectRow['projectDate'];
		$projectCatId = $getProjectRow['projectCatId'];
		$getprojectCatNameSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCatName = mysqli_query($connF, $getprojectCatNameSql);
		$getprojectCatNameRow = mysqli_fetch_array($getprojectCatName);
		$projectCatName = $getprojectCatNameRow['projectCatName'];

		$projectstatusId = $getProjectRow['projectstatusId'];
		$projectstatusSql = "SELECT * FROM projectstatus WHERE projectstatusId='$projectstatusId'";
		$getprojectstatus = mysqli_query($connF, $projectstatusSql);
		$getprojectstatusRow = mysqli_fetch_array($getprojectstatus);
		$projectstatus = $getprojectstatusRow['projectstatus'];
		echo "
			<tr>
				<td>$projectId</td>
				<td>$projectName</td>
				<td>$projectDesc</td>
				<td>$projectLoc</td>
				<td>$projectDate</td>
			<td><img src='resources/project_img/$projectImg' style='width: 50px;height:50px;'></td>

				<td>$projectCatName</td>
				<td>$projectstatus</td>
				<td><a href='index.php?editproject=$projectId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
		<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProject=$projectId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}

// End View Project 

// Start Delete Project
function deleteProject()
{
	global $connF;
	if (isset($_GET['deleteProject'])) {

		$ProjectId = $_GET['deleteProject'];
		$deleteProjectSql = "DELETE FROM project WHERE projectId='$ProjectId'";
		$deleteProject = mysqli_query($connF, $deleteProjectSql);
		if ($deleteProject) {
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	}

}
// End Delete Project

// Count Project Status Id 1

function countUpcoming()
{

	global $connF;
	$getUpcomingDetailSql = "SELECT * FROM project WHERE projectstatusId=1";
	$getUpcomingDetail = mysqli_query($connF, $getUpcomingDetailSql);
	$UpcomingCount = mysqli_num_rows($getUpcomingDetail);

	echo "$UpcomingCount";
}
function countOngoing()
{

	global $connF;
	$getOngoingDetailSql = "SELECT * FROM project WHERE projectstatusId=2";
	$getOngoingDetail = mysqli_query($connF, $getOngoingDetailSql);
	$OngoingCount = mysqli_num_rows($getOngoingDetail);

	echo "$OngoingCount";
}

function countCompleted()
{

	global $connF;
	$getCompletedDetailSql = "SELECT * FROM project WHERE projectstatusId=3";
	$getCompletedDetail = mysqli_query($connF, $getCompletedDetailSql);
	$CompletedCount = mysqli_num_rows($getCompletedDetail);

	echo "$CompletedCount";
}
// Start Add Vacancy
function addVacancy()
{
	global $connF;

	if (isset($_POST['addnewvacancy'])) {
		// Sanitize input
		$postName = mysqli_real_escape_string($connF, $_POST['postName']);
		$experience = mysqli_real_escape_string($connF, $_POST['experience']);
		$no_vacancies = mysqli_real_escape_string($connF, $_POST['no_vacancies']);
		$qualification = mysqli_real_escape_string($connF, $_POST['qualification']);
		$jobdescription = mysqli_real_escape_string($connF, $_POST['jobdescription']);
		$jobtype = mysqli_real_escape_string($connF, $_POST['jobtype']);
		$skill1 = mysqli_real_escape_string($connF, $_POST['skill1']);
		$location1 = mysqli_real_escape_string($connF, $_POST['location1']);

		// SQL query
		$addVacancySql = "INSERT INTO vacancy(postName, experience, no_vacancies, qualification, jobdescription, jobtype, skill1, location1) VALUES ('$postName', '$experience', '$no_vacancies', '$qualification', '$jobdescription', '$jobtype', '$skill1', '$location1')";

		// Execute query
		$addVacancy = mysqli_query($connF, $addVacancySql);

		// Check for errors
		if (!$addVacancy) {
			echo "Error: " . mysqli_error($connF); // This line checks for errors in the query execution
		} else {
			echo "<script>alert('Vacancy Added')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	}
}

// End Add Vacancy

// Start View Vacancy

function displayVacancy()
{
	global $connF;
	$getVacancySql = "SELECT * FROM vacancy WHERE 1";
	$getVacancy = mysqli_query($connF, $getVacancySql);
	while ($getVacancyRow = mysqli_fetch_array($getVacancy)) {
		$vacancyId = $getVacancyRow['vacancyId'];
		$postName = $getVacancyRow['postName'];
		$no_vacancies = $getVacancyRow['no_vacancies'];
		$experience = $getVacancyRow['experience'];
		$qualification = $getVacancyRow['qualification'];
		$jobdescription = $getVacancyRow['jobdescription'];
		$jobtype = $getVacancyRow['jobtype'];
		$skill1 = $getVacancyRow['skill1'];
		$location1 = $getVacancyRow['location1'];
		// 		$vacancyheaderTxt = $getVacancyRow['vacancyheaderTxt'];
// 		$vacancyheaderImage = $getVacancyRow['vacancyheaderImage'];
		echo "
			<tr>
				<td>$vacancyId</td>
				<td>$postName</td>
				<td>$no_vacancies</td>
				<td>$experience</td>
				<td>$qualification</td>
				<td>$jobdescription</td>
				<td>$jobtype</td>
				<td>$skill1</td>
				<td>$location1</td>
				
				<td><a href='index.php?editvacancy=$vacancyId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteVacancy=$vacancyId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}

// Start Edit Vacancy

function updateVacancy()
{

	global $connF;

	if (isset($_POST['updatevacancy'])) {

		$vacancyId = $_GET['editvacancy'];

		$getVacancySql = "SELECT * FROM vacancy WHERE vacancyId='$vacancyId'";
		$getVacancy = mysqli_query($connF, $getVacancySql);
		$getVacancyRow = mysqli_fetch_array($getVacancy);
		$postName = $_POST['postName'];
		$experience = $_POST['experience'];
		$no_vacancies = $_POST['no_vacancies'];
		// 		$vacancyheaderTxt = $_POST['vacancyheaderTxt'];
		$qualification = $_POST['qualification'];
		$jobdescription = $_POST['jobdescription'];
		$jobtype = $_POST['jobtype'];
		$skill1 = $_POST['skill1'];
		$location1 = $_POST['location1'];
		// 		$vacancyheaderImageOld = $getVacancyRow['vacancyheaderImage'];
// 		$vacancyheaderImage = $_FILES['vacancyheaderImage']['name'];

		if (empty($vacancyheaderImage)) {
			$vacancyheaderImage = $vacancyheaderImageOld;
		}
		$tempImg1 = $_FILES['vacancyheaderImage']['tmp_name'];
		move_uploaded_file($tempImg1, "resources/$vacancyheaderImage");

		$updateVacancySql = "UPDATE vacancy SET postName='$postName',experience='$experience',no_vacancies='$no_vacancies',qualification='$qualification',jobdescription='$jobdescription',jobtype='$jobtype',skill1='$skill1',location1='$location1' WHERE vacancyId='$vacancyId'";
		$updateVacancy = mysqli_query($connF, $updateVacancySql);
		if ($updateVacancy) {
			echo "<script>alert('Vacancy Updated')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		} else {
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	}
}
// End Edit Vacancy

// Start Delete Vacancy
function deleteVacancy()
{
	global $connF;
	if (isset($_GET['deleteVacancy'])) {

		$VacancyId = $_GET['deleteVacancy'];
		$deleteVacancySql = "DELETE FROM vacancy WHERE vacancyId='$VacancyId'";
		$deleteVacancy = mysqli_query($connF, $deleteVacancySql);
		if ($deleteVacancy) {
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	}

}
// End Delete Vacancy

// Count Vacancy

function addAppointment()
{
	global $connF;

	if (isset($_POST['bookapointment'])) {
		// Retrieve and sanitize form data
		$firstname = htmlspecialchars(trim($_POST['firstname']));
		$lastname = htmlspecialchars(trim($_POST['lastname']));
		$mobile = htmlspecialchars(trim($_POST['mobile']));
		$gender = htmlspecialchars(trim($_POST['gender']));
		$age = htmlspecialchars(trim($_POST['age']));
		$email = htmlspecialchars(trim($_POST['email']));

		// Check if the appointment already exists in the database
		$checkAppointmentSql = "SELECT * FROM appointments WHERE email = '$email' AND mobile = '$mobile' AND firstname = '$firstname' AND lastname = '$lastname'";
		$checkAppointment = mysqli_query($connF, $checkAppointmentSql);

		if (mysqli_num_rows($checkAppointment) > 0) {
			echo "<script>alert('This appointment has already been booked.')</script>";
		} else {
			// Insert data into the database
			$addAppointmentSql = "INSERT INTO appointments (firstname, lastname, email, mobile, gender, age) 
                                   VALUES ('$firstname', '$lastname', '$email', '$mobile', '$gender', '$age')";
			$addAppointment = mysqli_query($connF, $addAppointmentSql);

			// Check if the appointment was added successfully
			if ($addAppointment) {
				echo "<script>alert('Appointment booked successfully!')</script>";
				echo "<script>window.open('index.php','_self')</script>";
			} else {
				echo "<script>alert('Failed to book appointment. Please try again.')</script>";
			}
		}
	}
}




function countVacancy()
{

	global $connF;
	$getVacancyDetailSql = "SELECT * FROM vacancy WHERE 1";
	$getVacancyDetail = mysqli_query($connF, $getVacancyDetailSql);
	$VacancyCount = mysqli_num_rows($getVacancyDetail);

	echo "$VacancyCount";
}
// Start Add Clients

function addClient()
{
	global $connF;
	if (isset($_POST['addnewclient'])) {

		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];
		$tempImg1 = $_FILES['clientImage']['tmp_name'];
		move_uploaded_file($tempImg1, "resources/client_img/$clientImage");
		$addClientSql = "INSERT INTO clients(clientName,clientImage) VALUES ('$clientName','$clientImage')";
		$addClient = mysqli_query($connF, $addClientSql);
		if ($addClient) {
			echo "<script>alert('Client Added')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}

	}
}

// End Add Clients


// Start View Clients
function displayClient()
{
	global $connF;
	$getClientSql = "SELECT * FROM clients WHERE 1";
	$getClient = mysqli_query($connF, $getClientSql);
	while ($getClientRow = mysqli_fetch_array($getClient)) {
		$clientId = $getClientRow['clientId'];
		$clientName = $getClientRow['clientName'];
		$clientImage = $getClientRow['clientImage'];
		echo "
			<tr>
				<td>$clientId</td>
				<td>$clientName</td>
				<td><img src='resources/client_img/$clientImage' style='width: 50px;height:50px;'></td>
                <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteClient=$clientId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
                <td><a href='index.php?editclient=$clientId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}
// End View Clients

// Start Edit Clients
function updateClient()
{

	global $connF;

	if (isset($_POST['updateclient'])) {

		$clientId = $_GET['editclient'];

		$getClientSql = "SELECT * FROM clients WHERE clientId='$clientId'";
		$getClient = mysqli_query($connF, $getClientSql);
		$getClientRow = mysqli_fetch_array($getClient);

		$clientImageOld = $getClientRow['clientImage'];
		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];

		if (empty($clientImage)) {
			$clientImage = $clientImageOld;
		}

		$tempImg1 = $_FILES['clientImage']['tmp_name'];

		// Move the new image
		move_uploaded_file($tempImg1, "resources/client_img/$clientImage");

		// Remove the old image if the new image is uploaded
		if (!empty($clientImage) && $clientImage !== $clientImageOld) {
			if (file_exists("resources/client_img/$clientImageOld")) {
				unlink("resources/client_img/$clientImageOld");
			}
		}

		$updateClientSql = "UPDATE clients SET clientName='$clientName', clientImage='$clientImage' WHERE clientId='$clientId'";
		$updateClient = mysqli_query($connF, $updateClientSql);
		if ($updateClient) {
			echo "<script>alert('Client Updated')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		} else {
			echo "<script>alert('Something went wrong!')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	}
}
// Start Delete Client
function deleteClient()
{
	global $connF;
	if (isset($_GET['deleteClient'])) {

		$ClientId = $_GET['deleteClient'];

		// Get the client image before deleting the record
		$getClientSql = "SELECT clientImage FROM clients WHERE clientId='$ClientId'";
		$getClient = mysqli_query($connF, $getClientSql);
		$getClientRow = mysqli_fetch_array($getClient);

		$clientImage = $getClientRow['clientImage'];

		// Delete the client record from the database
		$deleteClientSql = "DELETE FROM clients WHERE clientId='$ClientId'";
		$deleteClient = mysqli_query($connF, $deleteClientSql);

		if ($deleteClient) {
			// Remove the image from the folder
			if (!empty($clientImage) && file_exists("resources/client_img/$clientImage")) {
				unlink("resources/client_img/$clientImage");
			}

			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	}
}

// End Delete Client

// Start Add Contact Us

function addContactUs()
{
	global $connF;

	if (isset($_POST['addnewcontact'])) {

		// Collect POST data
		$contactAddress = trim($_POST['contact_address']);
		$contactEmail_1 = trim($_POST['contact_email1']);
		$contactEmail_2 = trim($_POST['contact_email2']);
		$contactNum_1 = trim($_POST['contact_num1']);
		$contactNum_2 = trim($_POST['contact_num2']);
		$working_hours = trim($_POST['working_hours']);

		// Check if any field is empty
		if (
			empty($contactAddress) ||
			empty($contactEmail_1) ||
			empty($contactEmail_2) ||
			empty($contactNum_1) ||
			empty($contactNum_2) ||
			empty($working_hours)
		) {
			echo "<script>alert('All fields are mandatory. Please fill out every field.')</script>";
			return;
		}

		// Insert data into database
		$addContactSql = "INSERT INTO contactus (contact_address, contact_email1, contact_email2, contact_num1, contact_num2, working_hours) 
		                  VALUES ('$contactAddress', '$contactEmail_1', '$contactEmail_2', '$contactNum_1', '$contactNum_2', '$working_hours')";

		$addContact = mysqli_query($connF, $addContactSql);

		if ($addContact) {
			echo "<script>alert('Contact Added')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		} else {
			// Display MySQL error for debugging
			$error = mysqli_error($connF);
			echo "<script>alert('Failed to add contact. Error: $error')</script>";
		}
	}
}



// End Add Contact Us

// Start View Contact Us

function displayContactUs()
{
	global $connF;
	$getContactSql = "SELECT * FROM contactus WHERE 1";
	$getContact = mysqli_query($connF, $getContactSql);
	while ($getContactRow = mysqli_fetch_array($getContact)) {
		$contactId = $getContactRow['id'];
		$contactAddress = $getContactRow['contact_address'];
		$contactEmail_1 = $getContactRow['contact_email1'];
		$contactEmail_2 = $getContactRow['contact_email2'];

		$contactNum_1 = $getContactRow['contact_num1'];
		$contactNum_2 = $getContactRow['contact_num2'];
		$working_hours = $getContactRow['working_hours'];

		echo "
			<tr>
				<td>$contactId</td>
				<td>$contactAddress</td>
				<td>$contactEmail_1</td>
				<td>$contactEmail_2</td>
				
				<td>$contactNum_1</td>
				<td>$contactNum_2</td>
				<td>$working_hours</td>
				
		
                <td><a href='index.php?editcontact=$contactId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}

// End View Contact Us

// Start Edit Contact Us
function updateContact()
{
	global $connF;
	if (isset($_POST['updatecontact'])) {

		$contactId = $_GET['editcontact'];

		$getContactSql = "SELECT * FROM contactus WHERE id='$contactId'";
		$getContact = mysqli_query($connF, $getContactSql);
		$getContactRow = mysqli_fetch_array($getContact);

		$contactAddress = $_POST['contact_address'];
		$contactEmail_1 = $_POST['contact_email1'];
		$contactEmail_2 = $_POST['contact_email2'];
		$contactNum_1 = $_POST['contact_num1'];
		$contactNum_2 = $_POST['contact_num2'];
		$working_hours = $_POST['working_hours'];

		$updateContactSql = "
			UPDATE contactus
			SET 
				contact_address = '$contactAddress',
				contact_email1 = '$contactEmail_1',
				contact_email2 = '$contactEmail_2',
				contact_num1 = '$contactNum_1',
				contact_num2 = '$contactNum_2',
				working_hours = '$working_hours'
			WHERE id = '$contactId'
		";
		$updateContact = mysqli_query($connF, $updateContactSql);

		if ($updateContact) {
			echo "<script>alert('Contact Updated')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		} else {
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		}
	}
}

// End Edit Contact Us



